name: swallow_app
description: App de bolsa de empleo - Swallow
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^13.0.0

  # Network & Images
  http: ^1.2.0
  cached_network_image: ^3.3.1

  # Storage
  shared_preferences: ^2.2.2

  # Utils
  url_launcher: ^6.2.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/images/logo_nombre.png
    - assets/images/LogoPropoL_Negro.png
    - assets/images/from_md.png

  # Fonts
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
